### PR TITLE
Replaced copy of addon-sdk with download script.

### PR DESCRIPTION
**Pull request by peacememories**
Related to #8

This downloads the newest version of jetpack/cfx whenever the package is published

### CODE REVIEW

**Comment by peacememories** [comment]
I'm kind of nervous about merging this, because it could potentialy break the whole package. Could anyone of you sanity check my changes? (you'll need to checkout the branch in the repo, github diff gives up after a few hundred files).
You'll need to do an `npm install` to get the prepublish hook to run.
Tests complete successfully for what it's worth.

**Comment by peacememories** [comment]
An alternative to downloading the newest version of cfx would be to download a specific version. This would keep our cfx versions from suddenly jumping with releases that have nothing to do with it.

**Comment by peacememories** [comment]
@jsantell @PixnBits thoughts?

**Comment by jsantell** [comment]
How about as a build step in the package.json, it fetches the latest SDK? CFX won't be updated anymore anyway. Or, require a path to the sdk locally via argument or env var and this just interfaces with it

**Comment by peacememories** [comment]
This is what the change in this pull request does. The only build step hook we really got is pre-publish, so I'm using that.
Since the tests run on my linux box (though not on windows, which the old tests didn't either) and I've tested a bit with a personal project, I'm going to merge this now.

**Pull request merged**
